### PR TITLE
Fix #3

### LINKED ISSUE #3: Online converter doesn't work
Looks like that online converter doesn't work.

### PR DESCRIPTION
**Pull request by Cl0v1s**
Fixed Uncaught ReferenceError: fetchHTML is not defined
at HTMLButtonElement.onclick (index.html:19)

* Added dependencies in package.json
* Changed references in index.html since "Bad Gateway"
* Added browserify compatibility to package.json
* Renamed index.js to main.js
* "Compiled" main.js to index.js with browserify

### CODE REVIEW

**Comment by gunar** [comment]
Thank you. The build process seems to be broken, though. Am I doing something wrong?

**Comment by Clovis-Portron** [comment]
I don't think so ! I've "patched" browserify on it (adding "browser" key in package.json, and filled the "dependencies" key). Maybe I've done something wrong when adding stuff in the dependencies key ? 

I do not think we use the same building process since I only used browserify (I'm pretty new to all theese things), what's is yours ? :)

**Comment by gunar** [comment]
@Clovis-Portron Ok cool. But what command are you using to run it?

**Comment by Clovis-Portron** [comment]
Simply `browserify main.js -o index.js` in the root folder.

But anyway, I will repare the building process and commit it her :)

**Comment by gunar** [comment]
@Clovis-Portron That would be awesome.

Btw, `browserify main.js -o index.js` throws as there is no file named `main.js`.
My guess is that you forgot to commit some changes.

Let me know how I can help you!

**Comment by matbrik** [comment]
@gunar look at @Clovis-Portron first message, I guess that he renamed your index.js to main.js then he calls browserize to generate a new index.js made of all the dependencies grouped together in a single file from main.js

**Comment by gunar** [comment]
Alright. I am merging this.
It seems to work, and it seems people want it.
I'll fix the build script myself.

@Clovis-Portron @matbrik Thank you!

**Comment by gunar** [comment]
Seems to be working, let me know otherwise:
> http://gunar.github.io/medium-converter

**Pull request merged**
